### ISSUE TITLE
bug: doesn't read all tags

### ISSUE THREAD

**Issue by bcorrigan** [danigm/epub-rs#2]
Hello,

I think there might be a small bug with the metadata parsing.

According to the OPF spec, an epub can have multiple subject elements. The subject element is displayed as "tags" eg in calibre - it is not unusual for an epub to have half a dozen tags associated with it.

However, as you know, the metadata in epub-rs is dumped into a HashMap keyed on the element name. So, if there are multiple subject elements present, it appears to just silently overwrite each time, so that programmatically it is only possible to extract one value, whichever one was written last.

This means that if a book has multiple tags, epub-rs will only let you extract one of them.

Thanks much (and thanks for the lib)

**Comment by danigm** [comment]
I've just fixed this:
https://github.com/danigm/epub-rs/commit/6a51919b040a5426d087556400230ae7c9a2a096

Now metadata contains a HashMap<String, Vec<String>>, and the mdata method returns the first ocurrence.

**Comment by bcorrigan** [comment]
Works a treat, cheers!
