### ISSUE TITLE
Relicensing to more permissive license?

### ISSUE THREAD

**Issue by philippeitis** [danigm/epub-rs#21]
Hi, I was wondering if you would consider re-licensing this crate to something more permissive, such as MIT/Apache. I noticed that this crate uses a GPL license, which seems unecessarily restrictive, and it might prevent use of this crate in other open source projects (since it forces any dependent crates to also use the GPL license), which isn't necessarily desirable. I was wondering if there was a particular reason for using this license, since none of this crate's dependencies use the GPL license, and I don't see any other benefits for using the GPL license, as this isn't a particularly complex crate.

**Comment by danigm** [comment]
Right now I'm not considering to re-licensing this. The main idea to use GPL is to enforce that this code and the derivative work will be always free software. I don't like the idea of proprietary software that uses my code for free.
