### ISSUE TITLE
File not Found by EpubDoc on Windows

### ISSUE THREAD

**Issue by SilverTorus** [danigm/epub-rs#24]
I opened an epub file using epub-rs, but was unable to properly access the files within. As a result, I was not able to read the chapters and subsequently print them. Then, I tested epub-rs using the same code below on one of my Linux machines and found that epub-rs works as expected. I suspected that something regarding the way the file path is constructed in prevents the proper file from being retrieved with the ZipArchive. I have created a pull request #23 with a fix that works for Windows and Linux. Feel free to change anything as you see fit.

**What I Did** 
Code: 
```rust
pub fn main() {
    let epubfile = "test.epub";
    let mut file = File::open(epubfile).unwrap();
    let mut buffer = Vec::new();

    file.read_to_end(&mut buffer).unwrap();

    let cursor = Cursor::new(buffer);

    let doc = EpubDoc::from_reader(cursor);

    let mut doc = doc.unwrap_or_else(|err| {
        eprintln!("An error occurred while processing the epub file: {}", err);
        process::exit(1);
    });

    let current = doc.get_current_str();
    println!("{:?}", current);
}
```

**What I Expected**
The output of the first chapter:
```rust
Ok("<?xml version=\"1.0\"?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.1//EN\" \"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\n  <head>\n    <title>\"Cover\"</title>\n  </head>\n  <body>\n    <div style=\"text-align: center\">\n      <img src=\"@public@vhost@g@gutenberg@html@files@28885@28885-h@images@cover.jpg\" alt=\"Cover\" style=\"max-width: 100%; \" />\n      \n    </div>\n  </body>\n</html>")
```

**What I Received**
The output:
```rust
Err(specified file not found in archive)
```

**System Specs**
Operating System: Windows 10 Pro
Version: 20H2
OS Build: 19042.685
Processor: Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz   3.50 GHz
Installed RAM: 48.0 GB
System Type: 64-bit operating system, x64-based processor
Graphics Card: NVIDIA GeForce GTX 1080 Ti

**Comment by danigm** [comment]
I've just merged the PR, so I think this is fixed now. Thank you!
