### ISSUE TITLE
bug: Assumes that meta tag always has name and content attributes

### ISSUE THREAD

**Issue by bcorrigan** [danigm/epub-rs#3]
Hello,

I think I found a small bug that causes epub-rs to be unable to parse a small percentage of epubs. 

When parsing the epub metadata, it assumes that all <meta> tags have both a name and content attribute. However, it seems to be possible from the spec (and in a small percentage of epubs) for a <meta> tag to not have these attributes, which means that the doc new() fn returns an Error.

Here is an example snippet from an epub:
 
```
    <dc:publisher>Penguin Publishing Group</dc:publisher>

    <dc:identifier opf:scheme="ISBN">978-0-698-18756-6</dc:identifier>

    <meta property="dcterms:modified">2015-08-10T18:12:03Z</meta>

    <meta name="cover" content="cover_img" />
```

I made a local fork of epub-rs which simply ignores any meta tags that lack the name and content attrs, that seems to resolve the issue.

Thanks much

**Comment by danigm** [comment]
If you've a fork with this fixed, you can make a Pull Request and I'll merge.

**Comment by bcorrigan** [comment]
Cool, it is a one liner so will raise PR later.
