### ISSUE TITLE
Update on crates.io

### ISSUE THREAD

**Issue by ShaddyDC** [danigm/epub-rs#30]
Hi, I was seeing if I could use this library in a wasm project. However, the published version cannot be compiled with the `wasm32-unknown-unknown` target because it relies on some C dependencies in the zip library. This has already been fixed in #28, but the change hasn't been pushed yet.
I'd appreciate if you could update it. :)

**Comment by danigm** [comment]
Thanks for the report! I've just created a new tag and release in crates.io: https://crates.io/crates/epub/1.2.4
