### ISSUE TITLE
Find the collection and and group position of an epub

### ISSUE THREAD

**Issue by thibaultamartin** [danigm/epub-rs#36]
When displaying several epubs, it can be useful to group together those belonging to a same collection (for example all the books of the Wayfarer series by Becky Chambers) and their position in that collection.

The [epub spec says this is defined by the meta property `belongs-to-collection`](https://www.w3.org/publishing/epub3/epub-packages.html#sec-belongs-to-collection). A real life example from one of my epubs is:

```xml
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:opf="http://www.idpf.org/2007/opf">
    <dc:title id="en_title" xml:lang="en">The Galaxy, and the Ground Within</dc:title>
    <dc:creator id="id">Becky Chambers</dc:creator>
[...]
    <opf:meta property="belongs-to-collection" id="id-2">Wayfarers</opf:meta>
    <opf:meta refines="#id-2" property="collection-type">series</opf:meta>
    <opf:meta refines="#id-2" property="group-position">4</opf:meta>
}</opf:meta>
  </metadata>
```

I don't think it's possible for me to find metadata _by property_ instead of _by id_ at the moment, which makes it impossible for me to retrieve the collection a book belongs to and its position in such a collection.

**Comment by thibaultamartin** [comment]
My bad, this can actually be achieved with the following!

`doc.mdata("belongs-to-collection")` and `doc.mdata("group-position")`

**Comment by YaoLiMuMu** [comment]
How do I get all metadata, get all keys and values in HashMap,
`mdata()` must need an argument of type `&str`, I can't itterate it without `&str` in the `mdata()`,  and HashMap.len() is not support.
I am a newbie for rust, I'm sorry that my question may be more elementary i

**Comment by danigm** [comment]
> How do I get all metadata? get all keys and values in HashMap? `mdata()` must need an argument of type `&str`, I can't itterate it without `&str` in the `mdata()`, and HashMap.len() is not support. I am a newbie for rust, I'm sorry that my question may be more elementary i

You can iterate with the `metadata` hashmap, the `HashMap` implements an iterator, so it's easy to iterate over all the keys: https://doc.rust-lang.org/stable/std/collections/struct.HashMap.html#method.keys
