### ISSUE TITLE
bug: epubs with a Byte Order Mark (BOM) are not parsed

### ISSUE THREAD

**Issue by bcorrigan** [danigm/epub-rs#4]
Another small bug:

It is possible for utf-8 encoded XML to contain a Byte Order Mark (BOM) in the first few bytes of the file. Typically in the case of epubs, it is bytes: ef, bb, bf.

This seems to confuse whatever XML parser is used by epub-rs though, it results in an Error while creating the epub. This only affects a very few epubs but it appears they are a valid case.

I worked around this locally by putting in this ugly check in XMLReader, but presumably there is some nicer way! :

```
        if content[0]==0xefu8 && content[1]==0xbbu8 && content[2]==0xbfu8 {
            XMLReader {
                reader: ParserConfig::new()
                    .add_entity("nbsp", " ")
                    .add_entity("copy", "©")
                    .add_entity("reg", "®")
                    .create_reader(&content[3..])
            }
        } else {
            XMLReader {
                reader: ParserConfig::new()
                    .add_entity("nbsp", " ")
                    .add_entity("copy", "©")
                    .add_entity("reg", "®")
                    .create_reader(content)
            }
        }
```

It does appear to deal with the error at least - and the other BOMs (eg UTF-16 BOMs) don't seem to occur in practice for epubs.

I have attached an example container.xml from an epub with a BOM (from META-INF/container.xml).

[container.zip](https://github.com/danigm/epub-rs/files/1546093/container.zip)

Thanks!

**Comment by danigm** [comment]
I'm using this to parse xml: https://github.com/netvl/xml-rs

I don't know if this is for all XML or only for epubs. If it's for all XML we should report this issue to the xml-rs and try to send a patch. If it's only for epubs we can apply this code to the repo.

**Comment by bcorrigan** [comment]
I think it is valid part of an XML file. 

I will raise bug upstream then -   I suppose it is possible they think BOM is something to be dealt with when deserialising into Vec<u8> In the first place, depends on what they expect so will find out!

**Comment by bcorrigan** [comment]
It looks like someone already raised the issue with them some months ago:

https://github.com/netvl/xml-rs/issues/155

So I don't have much hope of them fixing it anytime soon. 

Perhaps I will try and find a nicer way to do workaround above and include in pull request?

**Comment by danigm** [comment]
You can send a patch related to this bug report. I've sent a patch some time ago and they accept it quickly. Meantime we can do this in the epub-rs, with your code.

https://github.com/netvl/xml-rs/pull/139

**Comment by bcorrigan** [comment]
I raised a PR to fix in xml-rs, lets see what happens.

https://github.com/netvl/xml-rs/pull/165

**Comment by bcorrigan** [comment]
Was digging about in xml-rs closed issues and discovered this: https://github.com/netvl/xml-rs/issues/10

It therefore seems that xml-rs will *not* handle the byte order mark by choice, so it has to be handled by callers of xml-rs.

Therefore, I will find some tidier way of doing it in epub-rs (eg, at file-open level if possible) and raise PR later.
