### ISSUE TITLE
Note linearity of spine items

### ISSUE THREAD

**Issue by LunarTulip** [danigm/epub-rs#46]
Currently, as far as I can tell from reading the docs, there's no way, for a given spine entry read out of an `EpubDoc`'s `spine`, to discern the value of its `linear` attribute. This is inconvenient; knowing a spine-entry's linearity is often useful and relevant to proper rendering of a book. Is there some method I'm missing by which the information can be accessed? If not, I'd recommend adding one.

**Comment by danigm** [comment]
Right now the spine in the doc struct is just a list of ids, but it could be easy to extend the current code to store a more complex object to store more information about each spine entry.

This is the code that retrieves the `idref` attr from each spine entry and stores it in the doc struct:
https://github.com/danigm/epub-rs/blob/master/src/doc.rs#L705-L711

```
    fn insert_spine(&mut self, item: &xmlutils::XMLNode) -> Result<(), DocError> {
        let id = item
            .get_attr("idref")
            .ok_or_else(|| XMLError::AttrNotFound("idref".into()))?;
        self.spine.push(id);
        Ok(())
    }
```

So a good idea could be to store a new struct for each spine entry with all the optional fields, https://www.w3.org/TR/epub-33/#dfn-itemref:
 * id
 * linear
 * properties
